version: '3'

services:
  app:
    build: .
    container_name: cloudflare-subdomain-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config.php:/var/www/html/config/config.php
    depends_on:
      - db
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=25M
      - PHP_POST_MAX_SIZE=25M

  db:
    image: mysql:8.0
    container_name: cloudflare-subdomain-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cloudflareNIC}
      MYSQL_USER: ${MYSQL_USER:-cloudflare}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cloudflarepassword}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./cloudflareNIC.sql:/docker-entrypoint-initdb.d/cloudflareNIC.sql

volumes:
  mysql_data: